## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
julia:
  - 0.6
  # - nightly
env:
  global:
    # Suppress "Could not connect to display" warnings from GR Framework.
    # * https://gr-framework.org/about.html#file-formats
    # * https://github.com/jheinen/gr/blob/v0.31.1/lib/gks/util.c#L67
    - GKS_WSTYPE: png
  matrix:
    - CI_GROUP=0
    - CI_GROUP=1
    - CI_GROUP=2
    - CI_GROUP=docs
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran

before_script:
  # Install packages required for the build to avoid re-installing
  # (some of) them in the after_success phase:
  - julia --color=yes ci/before_script.jl

  # Run some non-test portion of standard script here.  See also:
  # https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/julia.rb
  - julia --color=yes -e 'Pkg.clone(pwd())'
  - julia --color=yes -e 'Pkg.build("Bifurcations")'

script:
  - if [ "$CI_GROUP" = docs ]; then
    travis_wait 60 julia --color=yes docs/build.jl;
    else
    julia --color=yes --check-bounds=yes -e 'Pkg.test("Bifurcations"; coverage=true)';
    fi

after_success:
  # push coverage results to Coveralls
  - julia --color=yes -e 'cd(Pkg.dir("Bifurcations")); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia --color=yes -e 'cd(Pkg.dir("Bifurcations")); using Coverage; Codecov.submit(Codecov.process_folder())'
  # build documents
  - if [ "$CI_GROUP" = docs ]; then
    julia --color=yes docs/deploy.jl;
    fi
