## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
julia:
  - 0.6
  # - nightly
env:
  global:
    # Suppress "Could not connect to display" warnings from GR Framework.
    # * https://gr-framework.org/about.html#file-formats
    # * https://github.com/jheinen/gr/blob/v0.31.1/lib/gks/util.c#L67
    - GKS_WSTYPE: png
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Bifurcations"); Pkg.test("Bifurcations"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("Bifurcations")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Bifurcations")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # build documents
  - julia --color=yes -e 'Pkg.add.(("Documenter", "Plots", "QuickTypes"))'
  - julia --color=yes -e 'cd(Pkg.dir("Bifurcations")); include(joinpath("docs", "make.jl"))'
